name:                sfnt-tool
version:             0.1.0.0
github:              "AshleyYakeley/sfnt-tool"
license:             BSD3
author:              "Ashley Yakeley"
maintainer:          "ashley@semantic.org"
copyright:           "2022 Ashley Yakeley"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/AshleyYakeley/sfnt-tool#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- binary
- transformers

default-extensions:
- AllowAmbiguousTypes
- Arrows
- ConstraintKinds
- DataKinds
- DefaultSignatures
- EmptyCase
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- ForeignFunctionInterface
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImplicitParams
- NoImplicitPrelude
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- OverloadedLabels
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PatternSynonyms
- PolyKinds
- QuantifiedConstraints
- RankNTypes
- RecordWildCards
- RecursiveDo
- RoleAnnotations
- ScopedTypeVariables
- StandaloneDeriving
- StandaloneKindSignatures
- NoStarIsType
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeInType
- TypeOperators
- TypeSynonymInstances
- UndecidableInstances
- UndecidableSuperClasses
- ViewPatterns

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wcompat
- -Wnoncanonical-monad-instances
- -Wno-partial-type-signatures

executables:
  sfnt-tool:
    source-dirs: app
    main: Main.hs
    other-modules:
    - CharCode
    - Tables
    - OS2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
